version: '3'
networks:
  backend:
    driver: bridge

services:
  
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    working_dir: /var/www
    volumes:
      - ./:/var/www/laravel_studying/
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    ports:
      - 8080:80
    networks:
      - backend

  php:
    build: ./docker/php
    restart: always
    container_name: php
    working_dir: /var/www
    volumes:
      - ./:/var/www/laravel_studying/
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - backend  
    depends_on:
      - db

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - 6080:8080  
    networks:
      - backend    

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432  
    environment:
      POSTGRES_DB: database_laravel
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
    volumes: 
      - ./docker/postgres-data:/var/lib/postgresql/data
      - ./docker/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - backend      